def built_in_exception():
    return int("Not an integer")
